export const S = {
  page: { fontFamily: "'DM Sans',sans-serif", background: "var(--bg)", color: "var(--text)", minHeight: "100vh", overflowX: "hidden" },
  // Top bar
  topBar: { position: "sticky", top: 0, zIndex: 100, background: "rgba(245,243,238,.92)", backdropFilter: "blur(12px)", borderBottom: "1px solid var(--border)", padding: "0 20px" },
  topInner: { maxWidth: 1100, margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center", height: 52 },
  brand: { display: "flex", alignItems: "center", gap: 8, cursor: "pointer" },
  proBadge: { fontSize: 9, fontWeight: 800, background: "var(--gold)", color: "#fff", padding: "2px 6px", borderRadius: 4, letterSpacing: 1 },
  topRight: { display: "flex", alignItems: "center", gap: 8 },
  streakPill: { display: "flex", alignItems: "center", gap: 4, background: "#FFF5F0", border: "1px solid #F4D2C5", borderRadius: 20, padding: "4px 12px", fontSize: 13 },
  xpPill: { display: "flex", alignItems: "center", gap: 6, background: "var(--accent-light)", border: "1px solid var(--accent)", borderRadius: 20, padding: "4px 14px", fontSize: 13, cursor: "pointer" },
  achBtn: { display: "flex", alignItems: "center", gap: 4, background: "none", border: "1px solid var(--border)", borderRadius: 20, padding: "4px 12px", fontSize: 13, cursor: "pointer", fontFamily: "'DM Sans',sans-serif", color: "var(--text)" },
  achCount: { fontWeight: 700, fontSize: 12 },
  // Panels
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,.4)", zIndex: 200, display: "flex", justifyContent: "center", alignItems: "flex-start", padding: "60px 16px", overflowY: "auto" },
  panel: { background: "var(--surface)", borderRadius: 16, padding: "28px 24px", maxWidth: 480, width: "100%", maxHeight: "80vh", overflowY: "auto", boxShadow: "0 20px 60px rgba(0,0,0,.15)" },
  closeBtn: { background: "none", border: "none", fontSize: 20, cursor: "pointer", color: "var(--text-dim)", fontFamily: "'DM Sans'" },
  // Achievement popup
  achPopup: { position: "fixed", inset: 0, background: "rgba(0,0,0,.5)", zIndex: 300, display: "flex", justifyContent: "center", alignItems: "center", padding: 20, cursor: "pointer" },
  achPopupInner: { background: "var(--surface)", borderRadius: 20, padding: "36px 32px", textAlign: "center", maxWidth: 340, boxShadow: "0 24px 80px rgba(0,0,0,.2)", border: "2px solid var(--gold)" },
  // Level card
  lvCard: { display: "flex", alignItems: "center", gap: 16, background: "var(--surface)", borderRadius: "var(--radius)", padding: 20, border: "1px solid var(--border)" },
  xpBar: { height: 8, background: "var(--border)", borderRadius: 4, overflow: "hidden", marginTop: 6 },
  xpBarFill: { height: "100%", background: "var(--accent)", borderRadius: 4, transition: "width .5s ease" },
  statCard: { background: "var(--surface)", borderRadius: "var(--radius)", padding: 16, border: "1px solid var(--border)", textAlign: "center" },
  histItem: { display: "flex", alignItems: "center", gap: 10, padding: "10px 12px", background: "var(--bg)", borderRadius: 10, border: "1px solid var(--border)" },
  achCard: { display: "flex", alignItems: "center", gap: 12, padding: "12px 14px", background: "var(--bg)", borderRadius: 10, border: "1px solid var(--border)" },
  // Hero
  hero: { position: "relative", overflow: "hidden", background: "linear-gradient(165deg,#1B4332 0%,#2D6A4F 40%,#40916C 100%)", padding: "70px 24px 52px" },
  heroInner: { maxWidth: 850, margin: "0 auto", position: "relative", zIndex: 2 },
  heroBadge: { display: "inline-flex", alignItems: "center", gap: 6, background: "rgba(255,255,255,.1)", backdropFilter: "blur(8px)", border: "1px solid rgba(255,255,255,.12)", borderRadius: 50, padding: "5px 14px", fontSize: 12, fontWeight: 500, color: "#D8F3DC", marginBottom: 18, letterSpacing: .4 },
  heroTitle: { fontFamily: "'Playfair Display',serif", fontSize: "clamp(30px,5vw,46px)", fontWeight: 600, lineHeight: 1.15, color: "#fff", marginBottom: 14 },
  heroAccent: { fontStyle: "italic", color: "#95D5B2" },
  heroSub: { fontSize: "clamp(13px,1.7vw,16px)", lineHeight: 1.65, color: "rgba(255,255,255,.72)", maxWidth: 580, marginBottom: 28 },
  heroGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(130px,1fr))", gap: 10 },
  heroStat: { display: "flex", alignItems: "center", gap: 8, background: "rgba(255,255,255,.07)", backdropFilter: "blur(6px)", borderRadius: 10, padding: "10px 12px", border: "1px solid rgba(255,255,255,.08)" },
  heroOrb1: { position: "absolute", width: 300, height: 300, borderRadius: "50%", background: "radial-gradient(circle,rgba(149,213,178,.18) 0%,transparent 70%)", top: -70, right: -70, animation: "float 8s ease-in-out infinite" },
  heroOrb2: { position: "absolute", width: 220, height: 220, borderRadius: "50%", background: "radial-gradient(circle,rgba(212,168,83,.12) 0%,transparent 70%)", bottom: -50, left: -30, animation: "float 10s ease-in-out infinite 1s" },
  // Warning
  warn: { padding: "0 20px", marginTop: -14, position: "relative", zIndex: 3 },
  warnInner: { maxWidth: 700, margin: "0 auto", display: "flex", alignItems: "flex-start", gap: 10, background: "var(--warm-bg)", border: "1px solid var(--warm-border)", borderRadius: 10, padding: "12px 16px" },
  warnText: { fontSize: 13, lineHeight: 1.5, color: "#6B3A2A" },
  // Section
  sec: { padding: "40px 20px 60px" },
  secInner: { maxWidth: 1100, margin: "0 auto" },
  // Tabs
  tabs: { display: "flex", justifyContent: "center", gap: 6, marginBottom: 28, flexWrap: "wrap" },
  tabBtn: { padding: "8px 18px", borderRadius: 50, fontSize: 14, fontWeight: 500, fontFamily: "'DM Sans',sans-serif", background: "var(--surface)", color: "var(--text-dim)", border: "1px solid var(--border)" },
  tabActive: { background: "var(--accent-dark)", color: "#fff", borderColor: "var(--accent-dark)" },
  // Filter
  filterRow: { display: "flex", justifyContent: "center", gap: 6, flexWrap: "wrap", marginBottom: 24 },
  catBtn: { display: "inline-flex", alignItems: "center", gap: 5, padding: "7px 14px", borderRadius: 50, fontSize: 13, fontWeight: 500, fontFamily: "'DM Sans',sans-serif", background: "var(--surface)", color: "var(--text-dim)", border: "1px solid var(--border)" },
  catActive: { background: "var(--accent)", color: "#fff", borderColor: "var(--accent)" },
  // Grid
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(280px,1fr))", gap: 16 },
  card: { background: "var(--surface)", borderRadius: "var(--radius)", padding: 22, border: "1px solid var(--border)", display: "flex", flexDirection: "column", position: "relative" },
  doneBadge: { position: "absolute", top: 12, right: 12, width: 24, height: 24, borderRadius: "50%", background: "var(--accent)", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700 },
  cardIcon: { fontSize: 28, marginBottom: 10 },
  cardCat: { fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, color: "var(--accent)", marginBottom: 5 },
  cardTitle: { fontFamily: "'Playfair Display',serif", fontSize: 17, fontWeight: 500, marginBottom: 5 },
  cardDesc: { fontSize: 13, lineHeight: 1.55, color: "var(--text-dim)", flex: 1, marginBottom: 10 },
  cardMeta: { display: "flex", gap: 14, fontSize: 11, color: "var(--text-dim)", marginBottom: 12 },
  cardBtn: { display: "inline-flex", alignItems: "center", background: "transparent", border: "1px solid var(--accent)", color: "var(--accent)", borderRadius: 8, padding: "8px 16px", fontSize: 13, fontWeight: 600, fontFamily: "'DM Sans',sans-serif", alignSelf: "flex-start", transition: "all .2s" },
  showMore: { background: "transparent", border: "2px solid var(--accent)", color: "var(--accent)", borderRadius: 10, padding: "10px 22px", fontSize: 13, fontWeight: 600, fontFamily: "'DM Sans',sans-serif" },
  // Test
  testSec: { minHeight: "100vh", padding: "70px 20px 40px", background: "var(--bg)" },
  testInner: { maxWidth: 660, margin: "0 auto" },
  testHead: { marginBottom: 24 },
  backBtn: { background: "none", border: "none", color: "var(--accent)", fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans',sans-serif", marginBottom: 14, padding: 0 },
  timerBar: { height: 5, background: "var(--border)", borderRadius: 3, overflow: "hidden" },
  timerFill: { height: "100%", borderRadius: 3, transition: "width 1s linear,background .3s" },
  progBar: { height: 3, background: "var(--border)", borderRadius: 2, overflow: "hidden" },
  progFill: { height: "100%", background: "var(--accent)", borderRadius: 2, transition: "width .3s" },
  qCard: { background: "var(--surface)", borderRadius: "var(--radius)", padding: "28px 24px", border: "1px solid var(--border)", animation: "fadeUp .3s ease" },
  qNum: { fontSize: 12, fontWeight: 700, color: "var(--accent)", textTransform: "uppercase", letterSpacing: .7, marginBottom: 10 },
  qText: { fontFamily: "'Playfair Display',serif", fontSize: 19, fontWeight: 500, lineHeight: 1.4, marginBottom: 20 },
  optBtn: { display: "flex", alignItems: "center", gap: 10, background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 10, padding: "12px 16px", fontSize: 14, fontFamily: "'DM Sans',sans-serif", textAlign: "left", width: "100%", color: "var(--text)" },
  optL: { display: "inline-flex", alignItems: "center", justifyContent: "center", width: 26, height: 26, borderRadius: 7, background: "var(--accent-light)", color: "var(--accent-dark)", fontSize: 12, fontWeight: 700, flexShrink: 0 },
  likBtn: { display: "flex", flexDirection: "column", alignItems: "center", gap: 6, background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 10, padding: "14px 10px", fontSize: 13, fontFamily: "'DM Sans',sans-serif", textAlign: "center", color: "var(--text)" },
  rBox: { width: "100%", padding: "52px 16px", borderRadius: 14, fontSize: 22, fontWeight: 700, fontFamily: "'Playfair Display',serif", border: "none", textAlign: "center" },
  stroopBtn: { padding: "12px 24px", borderRadius: 10, border: "none", color: "#fff", fontSize: 15, fontWeight: 700, fontFamily: "'DM Sans',sans-serif", minWidth: 90 },
  // Result
  resCard: { background: "var(--surface)", borderRadius: "var(--radius)", padding: "36px 28px", border: "1px solid var(--border)", textAlign: "center" },
  resBadge: { display: "inline-flex", alignItems: "center", justifyContent: "center", background: "var(--accent-light)", borderRadius: 14, padding: "18px 32px", border: "2px solid var(--accent)" },
  xpEarned: { display: "inline-block", background: "linear-gradient(135deg,#D4A853,#E8C97A)", color: "#fff", fontWeight: 700, fontSize: 14, padding: "5px 16px", borderRadius: 20, marginTop: 8 },
  resBar: { position: "relative", height: 28, background: "var(--bg)", borderRadius: 14, overflow: "hidden", marginTop: 16, border: "1px solid var(--border)" },
  resFill: { height: "100%", background: "linear-gradient(90deg,var(--accent),#52B788)", borderRadius: 14, transition: "width 1s ease" },
  resBarTxt: { position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", fontSize: 12, fontWeight: 600 },
  warnSmall: { display: "flex", alignItems: "flex-start", gap: 8, background: "var(--warm-bg)", border: "1px solid var(--warm-border)", borderRadius: 8, padding: "10px 12px", marginTop: 20, textAlign: "left" },
  // Recommendations
  recSection: { marginTop: 16 },
  recSummary: { display: "flex", alignItems: "center", gap: 14, background: "var(--surface)", borderRadius: "var(--radius)", padding: "20px 20px", border: "1px solid var(--border)", marginBottom: 16 },
  recTitle: { fontFamily: "'Playfair Display',serif", fontSize: 17, fontWeight: 600, marginBottom: 12, marginTop: 20 },
  tipCard: { display: "flex", alignItems: "flex-start", gap: 12, background: "var(--surface)", borderRadius: 12, padding: "16px 16px", border: "1px solid var(--border)", transition: "all .2s" },
  tipIcon: { width: 40, height: 40, borderRadius: 10, background: "var(--accent-light)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, flexShrink: 0 },
  proRef: { background: "linear-gradient(135deg,#D8F3DC,#E8F5E9)", borderRadius: 12, padding: "16px 18px", border: "1px solid #A7D7C5", marginTop: 16 },
  relCard: { display: "flex", alignItems: "center", gap: 10, background: "var(--surface)", borderRadius: 10, padding: "12px 14px", border: "1px solid var(--border)", cursor: "pointer", fontFamily: "'DM Sans',sans-serif", textAlign: "left", width: "100%", color: "var(--text)" },
  primBtn: { background: "var(--accent)", color: "#fff", border: "none", borderRadius: 10, padding: "11px 24px", fontSize: 14, fontWeight: 600, fontFamily: "'DM Sans',sans-serif" },
  secBtn: { background: "transparent", color: "var(--accent)", border: "2px solid var(--accent)", borderRadius: 10, padding: "11px 24px", fontSize: 14, fontWeight: 600, fontFamily: "'DM Sans',sans-serif" },
};
